name: Lingo.dev i18n

on:
  push:
    branches:
      - testbranch
    paths:
      - "messages/**"        
      - ".github/workflows/lingo.yml"

permissions:
  contents: write
  pull-requests: write

jobs:
  i18n:
    if: contains(github.event.head_commit.message, '#lingo') 
    name: Run i18n
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: lingodotdev/lingo.dev@main
        env:
          GH_TOKEN: ${{ github.token }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        with:
          api-key: ${{ secrets.LINGODOTDEV_API_KEY }}
          commit-message: "feat: update translations via lingo.dev"
          pull-request: true
          pull-request-base: testbranch
          pull-request-title: "feat: PR for Updating translations via @LingoDotDev"
          
